### ISSUE TITLE
allow_anonymous false

### ISSUE THREAD

**Issue by abe520** [0x2142/frigate-notify#1]
My mqtt Settings do not allow anonymous users, how should I change the config?

**Comment by 0x2142** [comment]
Hi there - Right now this app only supports anonymous MQTT users, since my lab is set up to allow anonymous. However, I can set up an MQTT server with authentication & update the code. 

Please allow me a few days & I'll update you once that's done

**Comment by 0x2142** [comment]
Hello again - I had some time last night to work on this. I've released a new version that contains support for MQTT authentication. It's working on my home set up right now - but please let me know if you have any issues!

Thanks!
