### ISSUE TITLE
send image in notification instead of URL

### ISSUE THREAD

**Issue by ProductiveAsparagus56** [0x2142/frigate-notify#101]
This is very similar to #98 but i think it is easier and faster to implement as it doesn't require transcoding or uploading a lot of data.

I would like this project to be able to send a picture instead of the frigate url.

**Comment by 0x2142** [comment]
Hi there - Which notification provider are you using? By default, all notifications will include sending the actual picture that Frigate has saved as a snapshot. The only one that sends a link instead is Gotify, but it doesn't support attaching images.

**Comment by freefd** [comment]
@ProductiveAsparagus56, the only thing I can advise here: switch to [Ntfy](ntfy.sh).
It's more flexible and human-friendly.

**Comment by freefd** [comment]
@ProductiveAsparagus56, 

>  Anyone could access ntfy.

You can check the Ntfy docs about ACL for [users and roles](https://docs.ntfy.sh/config/#users-and-roles).
The second part is the [authentication](https://docs.ntfy.sh/publish/#authentication) from a client, it's already [supported by custom headers](https://frigate-notify.0x2142.com/latest/config/file/#ntfy) for Ntfy notifier in the frigate-notify.
