### ISSUE TITLE
Support for sub_label

### ISSUE THREAD

**Issue by lubomir-moric** [0x2142/frigate-notify#102]
**Is your feature request related to a problem? Please describe.**
Using Frigate and Plate Recogniser. Plate Recogniser adds sub_label to recognised car licence plates, I would like to block events, when my car is recognised, by defining its licence plate in config like:¨
```
alerts:
  sublabels:
    block:
      - MY_PLATE_XYZ
```

**Describe the solution you'd like**
Possibility to allow/block notification based on sub_label (same functionality as with "label").

In MQTT there is attribute `sub_lablel`: `... "sub_label": ["MY_PLATE_XYZ", null] ...`, so should be possibly easy to scrape.

**Comment by 0x2142** [comment]
Thanks for the suggestion. I'm good with adding support for this 👍

**Comment by freefd** [comment]
Linking the https://github.com/0x2142/frigate-notify/issues/107 here.

**Comment by 0x2142** [comment]
Just released [v0.3.3](https://github.com/0x2142/frigate-notify/releases/tag/v0.3.3) which includes this! See the [docs](https://frigate-notify.0x2142.com/latest/config/file/#sublabels) for configuration
