### ISSUE TITLE
Adding bounding boxes to image previews in Pushover notification

### ISSUE THREAD

**Issue by b-boy-brown** [0x2142/frigate-notify#109]
Hi there! 

First of all... thank you for everyone's hard work on this tool. I was dreading having to set up HA purely to enable for notifications for Frigate, so this was a godsend!

The question I have - I've successfully configured Pushover to receive notifications, everything is firing correctly, but I can't seem to adjust any parameters in the included message image snapshot (specifically I'm looking to include bounding boxes in the image).

I've tinkered with camera level MQTT settings as per frigate's documentation, but changes to any parameters there don't seem to take effect? Am I messing in the wrong place? I can't quite figure out where Pushover is grabbing screenshots from.

Again, I'm just looking to include a bounding box in the preview. If this is not available, so be it!

Thanks!

**Comment by freefd** [comment]
Hi @b-boy-brown,

This request is about adding the [bbox=1](https://docs.frigate.video/integrations/api#get-apieventsidsnapshotjpg) parameter to the URLs [here](https://github.com/0x2142/frigate-notify/blob/main/events/mqtt.go#L123) and [here](https://github.com/0x2142/frigate-notify/blob/main/events/api.go#L91).

Perhaps the parameters `timestamp`, `crop` and `quality` would also be useful to define based on configuration.

**Comment by 0x2142** [comment]
Hi there - Just letting you know this was added in [v0.3.3](https://github.com/0x2142/frigate-notify/releases/tag/v0.3.3). Here's the [docs](https://frigate-notify.0x2142.com/latest/config/file/#general) for enabling this!

**Comment by b-boy-brown** [comment]
Amazing 😍
