### ISSUE TITLE
Failed to load config from file

### ISSUE THREAD

**Issue by helio58** [0x2142/frigate-notify#111]
Running docker with

version: "3.0"
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/dietpi_userdata/config.yml:/app/config.yml
    restart: unless-stopped

config.yml

frigate:
  server: 192.168.0.32:5000
  ignoressl: false
  # Public / internet-facing Frigate URL, if different from above server address
  public_url:

  # List of HTTP headers to send to Frigate, in format Header: Value
  headers:
    # Example:
    # - Authorization: Basic abcd1234

  # On startup, frigate-notify will check reachability of Frigate server
  startup_check:
    # Max number of attempts (Default: 5)
    attempts: 3
    # Interval between attempts, in seconds (Default: 30)
    interval: 30

  webapi:
    # Set to true to enable event collection via the web API
    enabled:
    # Interval between checking for new events, in seconds (Default: 30)
    interval:

  mqtt:
    # Set to true to enable event collection via MQTT
    enabled:true
    # MQTT host IP
    server: 192.168.0.243
    # MQTT host port. (Default: 1883)
    port:
    # MQTT Client ID (Default: frigate-notify)
    clientid:
    # MQTT Authentication. Leave both blank for anonymous
    username:
    password:
    # Optionally set custom topic prefix (Default: frigate)
    topic_prefix:

But getting error

2024/08/03 16:42:37 +0200 INF Frigate Notify - v0.3.2
2024/08/03 16:42:37 +0200 INF Starting...
2024/08/03 16:42:37 +0200 FTL Failed to load config from file! error="yaml: line 1: did not find expected key"

I have run out of ideas please could I  have same help?
Thanks

**Comment by helio58** [comment]
Move to node-red

**Comment by 0x2142** [comment]
Hi there - 
   Sorry this wasn't working. I was able to replicate your issue by using the config snip that you shared. There is a missing space for `enabled:true` under `mqtt`. If I modify the config to include the space (`enabled: true`), then the app started just fine.

Just wanted to note this, in case anyone else runs across this issue.

**Comment by helio58** [comment]
Thank you will try
