### ISSUE TITLE
minor documentation issue

### ISSUE THREAD

**Issue by simowilso** [0x2142/frigate-notify#112]
Nice utility, thank you!

**Describe the bug**
In config.yml,

server: xxx.xxx.xxx.xxx:5000 does not work
it only works with
server: http://xxx.xxx.xxx.xxx:5000

**Expected behavior**

either document this with an example, or accept the IP:port combination without the leading http:

**Comment by 0x2142** [comment]
Hi there, thanks for reporting this. Could you share any logs to show what happens for you? I'm not able to replicate this - if I use `server: 10.10.10.10:5000` for example, the app does start. Currently I have logic built in to automatically prepend `http://` if it's not in the config.

If yours is working correctly, you may see a message that states: `No protocol specified on Frigate Server. Assuming http://. If this is incorrect, please adjust the config file.`. This is just intended to let you know that there was no protocol, so we assume it's likely `http://` - but I can also adjust the wording of that message if it helps.

**Comment by simowilso** [comment]
Well how weird. I could've sworn it didn't start. However, I removed the http:// and it's still working. Sorry for the distraction, closing.
