### ISSUE TITLE
using binary with same config as docker got error sending gotify notification

### ISSUE THREAD

**Issue by divemasterjm** [0x2142/frigate-notify#122]
ubuntu lxc

using binary with same config as docker got error sending gotify notification
Aug 16 12:22:47 frigatenotify frigate-notify[393]: text/template.Must(...)
Aug 16 12:22:47 frigatenotify frigate-notify[393]:         /opt/hostedtoolcache/go/1.22.4/x64/src/text/template/helper.>
Aug 16 12:22:47 frigatenotify frigate-notify[393]: github.com/0x2142/frigate-notify/notifier.renderMessage({_, _}, {{0x>
Aug 16 12:22:47 frigatenotify frigate-notify[393]:         /home/runner/work/frigate-notify/frigate-notify/notifier/ale>
Aug 16 12:22:47 frigatenotify frigate-notify[393]: github.com/0x2142/frigate-notify/notifier.SendGotifyPush({{0x858300,>
Aug 16 12:22:47 frigatenotify frigate-notify[393]:         /home/runner/work/frigate-notify/frigate-notify/notifier/got>
Aug 16 12:22:47 frigatenotify frigate-notify[393]: created by github.com/0x2142/frigate-notify/notifier.SendAlert in go>
Aug 16 12:22:47 frigatenotify frigate-notify[393]:         /home/runner/work/frigate-notify/frigate-notify/notifier/ale>
Aug 16 12:22:47 frigatenotify systemd[1]: frigate-notify.service: Main process exited, code=exited, status=2/INVALIDARG>
Aug 16 12:22:47 frigatenotify systemd[1]: frigate-notify.service: Failed with result 'exit-code'.

a part from installing binary file do we need to install any other requirement?

**Comment by 0x2142** [comment]
Thank you for reporting this! I am able to replicate and figured out what is happening. Looks like the notification templates aren't being handled properly for the binary version. 

As a workaround for now, you can copy the [templates](https://github.com/0x2142/frigate-notify/tree/main/templates) directory into the same path as the binary. 

I've also got a fix for this queued up & it will be included in the next release 👍

**Comment by 0x2142** [comment]
Fix is now released in [v0.3.5](https://github.com/0x2142/frigate-notify/releases/tag/v0.3.5)
