### ISSUE TITLE
Set From address to use in SMTP alert

### ISSUE THREAD

**Issue by szafar** [0x2142/frigate-notify#123]
Hi.
    I am trying to use smtp fro frigate notifications. The configuration looks valid but any notification is dropped because I get this error message:  WRN Unable to send alert error="send failed: getting sender address: no FROM address set" event_id=xxx. How do you set the Frrom address?

Regards.

**Comment by freefd** [comment]
Hi @szafar, please provide the frigate-notify configuration you're using (do not forget to obscure sensitive things like credentials, etc).

The `FROM` field in a message will be populated from `user` configuration property of [SMTP notifier](https://frigate-notify.0x2142.com/latest/config/file/#smtp): https://github.com/0x2142/frigate-notify/blob/main/notifier/smtp.go#L32

Potentially, an incorrect configuration can occur if your SMTP relay does not require authentication and you have not set both `user` and `password` properties in the configuration. In this case, the SMTP notifier will set `FROM` field in the message as [empty string](https://github.com/0x2142/frigate-notify/blob/main/config/config.go).

**Comment by szafar** [comment]
Hi,
   I am still unable to configure as now I am getting this error when using
self signed certs:
         WRN Unable to send alert error="dial failed: tls: failed to verify
certificate: x509: cannot validate certificate for 192.168.X.X because it
doesn't contain any IP SANs"
I normally use letsencrypt certs but that causes another error:
         WRN Unable to send alert error="dial failed: 454 TLS currently
unavailable".
In this case the corresponding error in exim4 is:
         TLS error on connection from notify ( ) [172.18.0.3] (cert/key
setup: cert=yes key=yes): Error while reading file.
Trying to figure out what it is causing this.

Regards,

**Comment by szafar** [comment]
Hi,
   My SMTP config looks like this:

  smtp:
    enabled: true
    server: 192.168.X.Y
    port: 25
    tls: True
    user: notifier
    password: XXXX
    recipient: ***@***.***

Regards,

**Comment by szafar** [comment]
BTW followed this to configure my exim4 ...
https://ubuntu.com/server/docs/install-and-configure-exim4

**Comment by freefd** [comment]
```
WRN Unable to send alert error="dial failed: tls: failed to verify certificate: x509: cannot validate certificate for 192.168.X.X because it doesn't contain any IP SANs"
```

It seems there should be `ignoressl` option like other notifier modules have.

**Comment by 0x2142** [comment]
Agreed. I can bundle that into the next release

**Comment by bobemoe** [comment]
This will be good, I too have a SMTP with no user, although I just created one as a workaround ;)

**Comment by bobemoe** [comment]
Oh, "dial failed: server does not support SMTP AUTH" not such a cleaver workaround!

Any idea when this might be released? Or at least merged into dev? Might be nice if a docker image was build for PRs to allow testing before merge?

**Comment by 0x2142** [comment]
Hi @bobemoe - I just merged the changes into `dev` so you can try pulling that down to test if you like. Please let me know if you see any issues!

**Comment by bobemoe** [comment]
@0x2142 Thanks. This is tested and working as expected :)

**Comment by 0x2142** [comment]
New options added to [v0.3.5](https://github.com/0x2142/frigate-notify/releases/tag/v0.3.5), see [docs](https://frigate-notify.0x2142.com/latest/config/file/#smtp).
