### ISSUE TITLE
Question : ByPass Authorization for visualizing clip behind reverse proxy ?

### ISSUE THREAD

**Issue by Nonobis** [0x2142/frigate-notify#126]
I am behind Ngninx Proxy Manager, how do you bypass auth when clicking on video/.snapshot link on received notification ?

**Comment by freefd** [comment]
@Nonobis you should set `public_url` in the [configation settings](https://frigate-notify.0x2142.com/latest/config/file/) with inline `user:password@` notation.

But please note, this notation doesn't work with Telegram, it will [disable this link](https://github.com/0x2142/frigate-notify/issues/54#issuecomment-2148564526)

**Comment by Nonobis** [comment]
@freefd : I can encode password in base64 ? or it's must be in plain text ... it's not really secure

**Comment by freefd** [comment]
@Nonobis, well, a little longer explanation then :)

As per the [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1), this old known form has been marked as deprecated, but is still supported by any browser or http lib, and would work anyway.

I believe, your reverse proxy is authenticating requests already, so the possible solutions could be:

1. You may use a password keeper solution to manage your credentials for quick and easily insert them into auth request
 fields. Personally, I use the self-hosted [Vaultwarden](https://github.com/dani-garcia/vaultwarden) vault with [Bitwarden official apps](https://bitwarden.com/download/#downloads-web-browser) for webkit-based and gecko-based browsers on desktop, and [Keyguard](https://github.com/AChep/keyguard-app) for my phones.
2. You can try an OAuth2 based SSO approach with a public or self-hosted IAM where authentication will be done transparently (in most cases). Here are the examples for [Authentik](https://geekscircuit.com/set-up-authentik-sso-with-nginx-proxy-manager/), [Keycloak](https://joeeey.com/blog/selfhosting-sso-with-nginx-oauth2-proxy-part-2/), [Authelia](https://ambientnode.uk/authelia-npm/), and even [Google](https://ahmedmusaad.com/add-google-authentication-to-any-website-using-nginx-and-oauth-proxy/).

**Comment by Nonobis** [comment]
not working ... i will wait and hope for https://github.com/0x2142/frigate-notify/issues/98 to be implemented one as an alternative.

**Comment by johnwilson1969** [comment]
> @freefd : I can encode password in base64 ? or it's must be in plain text ... it's not really secure

just as a note, base64 is encoding, not encryption and is not really safer than plaintext. And the username:password@ gets translated into a basic auth header with the encoded username/password and if using SSL, they should be encrypted at that point. I certainly understand being hesitant to be use urls with username/password as can end up in your browsing history... or possibly cached somewhere. I do it, but I understand why others do not.

**Comment by freefd** [comment]
Hi there, can it be closed in favor of #98?
