### ISSUE TITLE
docker image for arm64

### ISSUE THREAD

**Issue by LeoRX** [0x2142/frigate-notify#13]
Hi Matt,

Just wondering if you are able to publish docker image for arm64 as well?  I got an error saying no matching manifest for linux/arm64/v8 in the manifest list entries.

Thanks.

**Comment by 0x2142** [comment]
Yeah absolutely! I can get that published in the next day or two 👍

**Comment by 0x2142** [comment]
Hey there - A new Docker package has been built for ARM. I was able to pull it down & test on an ARM box I have - but please let me know if you have any issues! 

Thanks!!

**Comment by LeoRX** [comment]
Hi Matt.  Thank you!  Confirming I'm able to pull down the image and have it working perfectly.
