### ISSUE TITLE
A quick way to arm/disarm notifications ?

### ISSUE THREAD

**Issue by ronzino83** [0x2142/frigate-notify#131]
When I am at home, i would like not to be alert-bombed while i move in front of my cameras.
Is there a quick way to enable/disable notifications instead opening the .yml config, edit and save it ?

You can suggest also workarounds like "stopping the docker container, using this method.... ... ...."

triggering devices for me can be
alexa
android terminal
shelly cloud devices
secret local web url (not available outside LAN)

thnaks

**Comment by freefd** [comment]
Hi @ronzino83, just turn off detection for the selected camera(s)  in your Frigate:
![image](https://github.com/user-attachments/assets/cfdf8ee9-6cfa-41c4-91bf-ffa841b2e40d)

**Comment by ronzino83** [comment]
> Hi @ronzino83, just turn off detection for the selected camera(s) in your Frigate:

This is a way, but would like not to turn detection off, as it can be useful to have an events list filled with detections even if you are at home just in case... I would be better to me a way to disarm just notifications

**Comment by freefd** [comment]
> I would be better to me a way to disarm just notifications

You can probably try using [quiet hours](https://frigate-notify.0x2142.com/latest/config/file/#quiet-hours).

**Comment by 0x2142** [comment]
I think this would probably be something to include for the future REST API (#125)

**Comment by ronzino83** [comment]
Yeah it would be great. I wonder if the easyest way should be like a biderectional interaction with mqtt or telegram or whatever client to client communication already implemente for notifications

**Comment by freefd** [comment]
@ronzino83,

> ... but eventually considered this as client OS feature with scheduled DND, where the client application (Ntfy, Telegram, etc.) respects that DND flag.
In this way the Frigate will keep recording, frigate-notify will send detected events, but your client will be silent.

from https://github.com/0x2142/frigate-notify/issues/107#issuecomment-2230532718

**Comment by ronzino83** [comment]
Any kind of dnd cant  be a solution as i dont know when and at what time i would like to enable notifications.

I would like to use notification like an house alarm: when i am leaving the house i would like to turn on and when i come in turn off. It should be done with something really easy like pressing a button ,visit an url,write few chars on a chat. More complicated solution are not feasible because they are not pratical as closing the house door with key. 

Best integration ever would be with one single action to enable not only the notification but also sound alarm PiR sensors windows sensor and so on... i mean the tradional alarm system.

**Comment by freefd** [comment]
@ronzino83, 
> It should be done with something really easy like pressing a button 

Ok then.

Ntfy Android app:
![image](https://github.com/user-attachments/assets/4ac6b098-83f3-474b-b866-b9b4fe499bc1)

Telegram:
![image](https://github.com/user-attachments/assets/82840566-33dc-44ed-800a-da902bf593d1)

**Comment by freefd** [comment]
Hi @ronzino83, is there any news?

**Comment by ronzino83** [comment]
Yeah i have given a try. Muting in telegram work as it should. I can consider it a sort of work around: notification does not arise, but i am floaded with snapshot images. Apart battery and cellular data consumpiton (as telegram messages are received but not notified to user attention), i can find tons of private life pictures in my phone gallery,so telegram bot image gallery should be flushed often 😀 to avoid tha such picture bombing reveals too much when you look at your gallery

**Comment by freefd** [comment]
@ronzino83,

> so telegram bot image gallery should be flushed often

Before I moved to the self-hosted Ntfy server, I had frigate-notify notifications to Telegram with the [auto-delete setting](https://telegram.org/blog/autodelete-inv2) enabled as "2 days". This could be the solution for your case.

**Comment by freefd** [comment]
@ronzino83, have you solved your issue? Can it be closed now?

**Comment by ronzino83** [comment]
Hi, yes it can be closed. Auto delete is a good workaround . Thanks for your help and for the application

**Comment by ronzino83** [comment]
It can be closed
