### ISSUE TITLE
Personalized api link

### ISSUE THREAD

**Issue by smartelnovo** [0x2142/frigate-notify#140]
I am using Homeassistant to expose frigate's api, when I receive the notification I get the external link that reads like this:

http://mydomain.tld:2053/api/events/1727636950.408531-11q0uk/clip.mp4 since my events is exposed by Home Assistant the link it does not work, it should read something like this:

https://mydomain.tld:2053/api/frigate/notifications/1727641201.654539-vr4jlr/Entree/clip.mp4

Would it be possible to add a way to personalize the link?

**Comment by freefd** [comment]
Hi @smartelnovo, you can construct the link the way you want using Templates functionality: https://frigate-notify.0x2142.com/latest/config/templates/

**Comment by smartelnovo** [comment]
How cool is that, I totally missed that part
