### ISSUE TITLE
time zone - help needed 

### ISSUE THREAD

**Issue by Mareckil** [0x2142/frigate-notify#146]
How to setup correct time zone for Copenhagen in notifications?

**Comment by 0x2142** [comment]
Hi there, 
   You can specify timezone using the `TZ` environment variable as shown [here](https://frigate-notify.0x2142.com/latest/install/#docker-recommended).

Then you could update your docker compose file to be similar to this:

```yaml
...
    environment:
      - TZ=Europe/Copenhagen
...
```

**Comment by freefd** [comment]
@Mareckil, 

Also do not forget to set `timeformat` in the configuration in accordance with [documentation](https://frigate-notify.0x2142.com/latest/config/file/#general):

```yaml
alerts:
  general:
    timeformat: 2024-01-01 00:00:00 CEST
```

**Comment by Mareckil** [comment]
Thanks for quick response
