### ISSUE TITLE
Better debugging for other templated fields

### ISSUE THREAD

**Issue by bobemoe** [0x2142/frigate-notify#155]
**Is your feature request related to a problem? Please describe.**

I am developing complex functionality in a templated header (example in #153) but debugging outputs are limited compared to a templated message.

When the app starts, its seems to load and parse any **message** templates on startup and report any **syntax errors** as fatal errors and refuse to start. Additionally when an alert is sent there is debug output showing the **final rendered content** generate from the template. Both these are very useful in debugging but seem to be **missing from templated headers** (and maybe other places templates are used?)

**Describe the solution you'd like**

Identical functionality that of the message template as described above.

**Comment by 0x2142** [comment]
That's a fair request - I'll see what I can do!

**Comment by 0x2142** [comment]
Just an FYI that I've merged a lot of this into the latest `dev` build 😊

**Comment by freefd** [comment]
@bobemoe is it still relevant or can it be closed as solved?

**Comment by bobemoe** [comment]
I haven't tested it yet but looking at the commits, it looks like you implemented what I requested! And a nice bit of code tidying/reuse too :) I'll open a new issue if I find anything unexpected when I do try it out. Cheers
