### ISSUE TITLE
How do you combine zones and unzoned cameras?

### ISSUE THREAD

**Issue by djdd87** [0x2142/frigate-notify#179]
Hey, great solution and I did have this working nicely. However, I have got 6 cameras in Frigate and I've setup a zone on one of the cameras on my driveway now called "drive".

What I'm seeing is that Frigate is correctly logging alerts/detections when someone enters a zone, but it still writes the events into mqtt. This means that Frigate-Notify is still sending me alerts.

Looking at the documentation, I can set:

```
unzoned: drop
allow: drive
```

But then I only get alerts from the driveway zone and not my other 5 cameras because they are "unzoned". Is the only solution here to create a zones for every other camera?

**Comment by freefd** [comment]
Hi @djdd87,

> But then I only get alerts from the driveway zone and not my other 5 cameras because they are "unzoned". 

see https://github.com/0x2142/frigate-notify/issues/66

**Comment by 0x2142** [comment]
Hi @djdd87 - Yes at the moment the `unzoned` setting is all-or-nothing across all cameras. Perhaps this may change in the future to allow more granular settings per camera, but for now the solution you suggested would be one way of working around this.

**Comment by djdd87** [comment]
Hey @0x2142 , that's fine then as long as I know that's the way I have to use it. I've just zoned all my cameras now and it seems to be working as intended. I'm no longer getting bombarded with the daily school traffic walking in front of my house.
