### ISSUE TITLE
is it possible to send and alert to more than one ntfy topic?

### ISSUE THREAD

**Issue by redlegoman** [0x2142/frigate-notify#183]
I have several cameras and I would like to send alerts for each camera to a different ntfy topic. Is this possible? perhaps with some sort of template?

**Comment by 0x2142** [comment]
It's almost possible - this is currently in progress with PR #182. Hoping to merge this into the `dev` branch this week & then it will be released with v0.4.0 shortly thereafter.

**Comment by redlegoman** [comment]
excellent! I look forward to trying it out
