### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by MaybeSomeMoor** [0x2142/frigate-notify#31]
Hello,
Would it be possible to add telegram to the list of notification methods please.

**Comment by 0x2142** [comment]
Hi there, 
   Thanks for your interest in this project! I don't currently use Telegram, so I may need some time to figure out how to integrate with it - but I can certainly start working on it. 

I'll let you know how it goes!

**Comment by 0x2142** [comment]
Awesome, Glad to hear it & Thanks for letting me know!
