### ISSUE TITLE
Add Pushover Notifications 

### ISSUE THREAD

**Issue by Tempura-so** [0x2142/frigate-notify#34]
Please can you add Pushover Notifications to frigate-notify https://pushover.net/

Thank you for creating frigate-notify, its excellent for standalone Frigate NVR

**Comment by 0x2142** [comment]
Hello there & thanks for using this project! I don't currently use Pushover, but I'm happy to set it up & get it working. 

I'll update you once I add this in 👍

**Comment by Tempura-so** [comment]
Thank you

**Comment by 0x2142** [comment]
Hi there, I've added Pushover support in the latest release: [v0.2.5](https://github.com/0x2142/frigate-notify/releases/tag/v0.2.5). Config info is in the [docs](https://frigate-notify.0x2142.com/config/#pushover)

**Comment by Tempura-so** [comment]
Pushover Notifications work perfectly, I am delighted, Thank you.
