### ISSUE TITLE
Driveway zone keeps being dropped

### ISSUE THREAD

**Issue by Tempura-so** [0x2142/frigate-notify#37]
Hello, I have an issue with a person on the driveway zone it gets dropped, I have proved the details below, thank you for your time.

previous config for zones - driveway dropped

  zones:
    # Allow notifications for events outside a zone
    # Set to `drop` to disallow this
    unzoned: drop
    # List of valid zones to generate alerts
    # If blank, all events with a zone will generate notifications
    allow:
    # List of zones to never generate notifications
    block:

current config for zones still driveway being dropped

  zones:
    # Allow notifications for events outside a zone
    # Set to `drop` to disallow this
    unzoned: drop
    # List of valid zones to generate alerts
    # If blank, all events with a zone will generate notifications
    allow:
     - driveway
     - left_pavement
     - right_pavement
     - side_path
     - top_patio
     - bottom_patio
    # List of zones to never generate notifications
    block:

cameras:
  Front_Garden: #Name for your Camera
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Front_Garden
        input_args: preset-rtsp-restream
        roles:
        - detect
        - audio
    audio: # <- enable audio events for all camera
      enabled: true
      max_not_heard: 30
      min_volume: 500
      listen:
      - scream
      - yell
      - glass
      - alarm
      - bang
      - breaking
      - tearing
      - smash
      - splinter
      - fire_alarm
      - smoke_detector
      - speech
    detect:
      enabled: true # Detection is enabled
      width: 640 # The Cameras resolution
      height: 480 # The Cameras resolution
    zones:
      driveway:
        coordinates: 
          0,339,64,381,59,421,88,480,263,480,555,480,573,408,591,249,591,129,419,117,247,111,215,113,126,145,36,187,0,204
      left_pavement:
        coordinates: 401,0,170,0,188,117,404,118
      right_pavement:
        coordinates: 640,0,404,0,404,118,598,135

frigate-notify  | 2024/03/30 20:35:52 Frigate Notify - v0.2.5
frigate-notify  | 2024/03/30 20:35:52 Starting...
frigate-notify  | 2024/03/30 20:35:52 Loading config file: ./config.yml
frigate-notify  | 2024/03/30 20:35:52 Validating config file...
frigate-notify  | 2024/03/30 20:35:52 MQTT Enabled.
frigate-notify  | 2024/03/30 20:35:52 Events outside a zone: drop
frigate-notify  | 2024/03/30 20:35:52 Zones to generate alerts for:
frigate-notify  | 2024/03/30 20:35:52  - driveway
frigate-notify  | 2024/03/30 20:35:52  - left_pavement
frigate-notify  | 2024/03/30 20:35:52  - right_pavement
frigate-notify  | 2024/03/30 20:35:52  - side_path
frigate-notify  | 2024/03/30 20:35:52  - top_patio
frigate-notify  | 2024/03/30 20:35:52  - bottom_patio
frigate-notify  | 2024/03/30 20:35:52 No zones excluded
frigate-notify  | 2024/03/30 20:35:52 Gotify alerting enabled.
frigate-notify  | 2024/03/30 20:35:52 Pushover alerting enabled.
frigate-notify  | 2024/03/30 20:35:52 Config file validated!
frigate-notify  | 2024/03/30 20:35:52 Config file loaded.
frigate-notify  | 2024/03/30 20:35:52 Connecting to MQTT Server...
frigate-notify  | 2024/03/30 20:35:52 App running. Press Ctrl-C to quit.
frigate-notify  | 2024/03/30 20:35:52 Connected to MQTT.
frigate-notify  | 2024/03/30 20:35:52 Subscribed to MQTT topic frigate/events
frigate-notify  | 2024/03/30 20:39:51 Event ID 1711831191.060235-h8taxr - Camera Front_Garden detected person in zone(s): []
frigate-notify  | 2024/03/30 20:39:51 Event ID 1711831191.060235-h8taxr - Start time: 2024-03-30 20:39:51 +0000 UTC
frigate-notify  | 2024/03/30 20:39:51 Event ID 1711831191.060235-h8taxr - Dropped since it was outside a zone.

Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831191.060235, 'snapshot': None, 'label': 'person', 'sub_label': None, 'top_score': 0.0, 'false_positive': True, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.67578125, 'box': [1, 193, 183, 479], 'area': 52052, 'ratio': 0.6363636363636364, 'region': [0, 124, 356, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 0, 'current_zones': [], 'entered_zones': [], 'has_clip': False, 'has_snapshot': False, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831191.460495, 'snapshot': {'frame_time': 1711831191.460495, 'box': [0, 189, 181, 476], 'area': 51947, 'region': [0, 140, 340, 480], 'score': 0.70703125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.70703125, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.70703125, 'box': [0, 189, 181, 476], 'area': 51947, 'ratio': 0.6306620209059234, 'region': [0, 140, 340, 480], 'stationary': False, 'motionless_count': 1, 'position_changes': 1, 'current_zones': [], 'entered_zones': [], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'new'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831191.460495, 'snapshot': {'frame_time': 1711831191.460495, 'box': [0, 189, 181, 476], 'area': 51947, 'region': [0, 140, 340, 480], 'score': 0.70703125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.70703125, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.70703125, 'box': [0, 189, 181, 476], 'area': 51947, 'ratio': 0.6306620209059234, 'region': [0, 140, 340, 480], 'stationary': False, 'motionless_count': 1, 'position_changes': 1, 'current_zones': [], 'entered_zones': [], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831192.060688, 'snapshot': {'frame_time': 1711831191.460495, 'box': [0, 189, 181, 476], 'area': 51947, 'region': [0, 140, 340, 480], 'score': 0.70703125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.71484375, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.6953125, 'box': [0, 202, 182, 478], 'area': 50232, 'ratio': 0.6594202898550725, 'region': [0, 144, 336, 480], 'stationary': False, 'motionless_count': 4, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831192.060688, 'snapshot': {'frame_time': 1711831191.460495, 'box': [0, 189, 181, 476], 'area': 51947, 'region': [0, 140, 340, 480], 'score': 0.70703125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.71484375, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.6953125, 'box': [0, 202, 182, 478], 'area': 50232, 'ratio': 0.6594202898550725, 'region': [0, 144, 336, 480], 'stationary': False, 'motionless_count': 4, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831197.260806, 'snapshot': {'frame_time': 1711831195.479761, 'box': [24, 159, 206, 477], 'area': 57876, 'region': [0, 92, 388, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.78125, 'box': [13, 163, 210, 477], 'area': 61858, 'ratio': 0.6273885350318471, 'region': [0, 108, 372, 480], 'stationary': False, 'motionless_count': 30, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831197.260806, 'snapshot': {'frame_time': 1711831195.479761, 'box': [24, 159, 206, 477], 'area': 57876, 'region': [0, 92, 388, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.78125, 'box': [13, 163, 210, 477], 'area': 61858, 'ratio': 0.6273885350318471, 'region': [0, 108, 372, 480], 'stationary': False, 'motionless_count': 30, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831201.45869, 'snapshot': {'frame_time': 1711831195.479761, 'box': [24, 159, 206, 477], 'area': 57876, 'region': [0, 92, 388, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.71484375, 'box': [0, 184, 211, 476], 'area': 61612, 'ratio': 0.7226027397260274, 'region': [0, 124, 356, 480], 'stationary': True, 'motionless_count': 51, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831201.45869, 'snapshot': {'frame_time': 1711831195.479761, 'box': [24, 159, 206, 477], 'area': 57876, 'region': [0, 92, 388, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.71484375, 'box': [0, 184, 211, 476], 'area': 61612, 'ratio': 0.7226027397260274, 'region': [0, 124, 356, 480], 'stationary': True, 'motionless_count': 51, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831206.460043, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.78125, 'box': [12, 165, 207, 473], 'area': 60060, 'ratio': 0.6331168831168831, 'region': [0, 116, 364, 480], 'stationary': True, 'motionless_count': 76, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831206.460043, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.78125, 'box': [12, 165, 207, 473], 'area': 60060, 'ratio': 0.6331168831168831, 'region': [0, 116, 364, 480], 'stationary': True, 'motionless_count': 76, 'position_changes': 1, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831213.857236, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.640625, 'box': [0, 223, 155, 477], 'area': 39370, 'ratio': 0.610236220472441, 'region': [0, 156, 324, 480], 'stationary': True, 'motionless_count': 113, 'position_changes': 1, 'current_zones': [], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831213.857236, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.640625, 'box': [0, 223, 155, 477], 'area': 39370, 'ratio': 0.610236220472441, 'region': [0, 156, 324, 480], 'stationary': True, 'motionless_count': 113, 'position_changes': 1, 'current_zones': [], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831215.256641, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.55859375, 'box': [17, 274, 129, 476], 'area': 22624, 'ratio': 0.5544554455445545, 'region': [0, 160, 320, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 2, 'current_zones': [], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831215.256641, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.55859375, 'box': [17, 274, 129, 476], 'area': 22624, 'ratio': 0.5544554455445545, 'region': [0, 160, 320, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 2, 'current_zones': [], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831215.458971, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.640625, 'box': [43, 288, 107, 405], 'area': 7488, 'ratio': 0.5470085470085471, 'region': [0, 160, 320, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 2, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'update'}
Received payload: {'before': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831215.458971, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': None, 'score': 0.640625, 'box': [43, 288, 107, 405], 'area': 7488, 'ratio': 0.5470085470085471, 'region': [0, 160, 320, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 2, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'after': {'id': '1711831191.060235-h8taxr', 'camera': 'Front_Garden', 'frame_time': 1711831215.458971, 'snapshot': {'frame_time': 1711831204.05758, 'box': [3, 176, 210, 478], 'area': 62514, 'region': [0, 124, 356, 480], 'score': 0.76953125, 'attributes': []}, 'label': 'person', 'sub_label': None, 'top_score': 0.796875, 'false_positive': False, 'start_time': 1711831191.060235, 'end_time': 1711831220.65575, 'score': 0.640625, 'box': [43, 288, 107, 405], 'area': 7488, 'ratio': 0.5470085470085471, 'region': [0, 160, 320, 480], 'stationary': False, 'motionless_count': 0, 'position_changes': 2, 'current_zones': ['driveway'], 'entered_zones': ['driveway'], 'has_clip': False, 'has_snapshot': True, 'attributes': {}, 'current_attributes': []}, 'type': 'end'}

**Comment by 0x2142** [comment]
Hi there,
   Thanks for reporting this issue & I appreciate you sharing config and logs! Are you using the web API or MQTT to query events? 

From the logs, I think that Frigate sends the event & initially the detected person is outside a zone. Then the event gets updated a bit later once the person enters the zone. However, the notification app only processed the initial event which had no zones associated. 

At the moment, my code only checks for **new** events & not event updates - since I wanted to reduce possible notification spam. Admittedly, I haven't used zones too much so this hasn't an issue for me yet. 

I've set up some test zones on one of my cameras & I'll see if I can recreate this. Then I'll just have to figure out how I might be able to consume & alert on updated events, but avoid sending too many notifications if there are a lot of updates.

**Comment by Tempura-so** [comment]
Thank you for looking into this, I am using  MQTT to query events.

**Comment by Tempura-so** [comment]
I forgot to mention could you give a option to be able to format the time IE %H:%M:%S %d/%m/%Y. and take account of daylight savings time as my Frigate Alerts are on behind, Thank you.

**Comment by 0x2142** [comment]
Hi there,
    I can probably add an option to modify the timestamp format - I'll add that to my list & see if I can get it in the next release👍

On the DST part - the code itself doesn't account for that, instead it is just pulling time from the local system & Frigate (if those are different). So, it may be that one of those systems could have incorrect time or time zone.

When an event is received, it contains the `start_time` info from Frigate. This is the timestamp that's used for alerts. If you have an event ID, like `1711831191.060235-h8taxr` in your logs above - you can check the timestamp from Frigate by going to `http://<your frigate instance>/api/events/1711831191.060235-h8taxr`. Check the `start_time` value & convert it from Unix timestamp with something like [this](https://unixtime.org/) site. 

With that timestamp from Frigate, the code itself just performs a conversion of the Unix timestamp. When it does this, it automatically picks up the local timezone on the system it's running on. So based on the logs, it looks like the system this code is running on is configured for the UTC timezone. 

In my case, I have Frigate & this notification app running on different docker hosts - so both of those host systems need to be in sync with NTP & have the correct time zones configured.

Also, just an update - I do have a working fix for the original issue, but I would like to test it a bit & make sure it works as expected. So I have the new dev version running side-by-side with the current released version right now. If it's all okay, I should be able to get this out in the next day or two.

**Comment by Tempura-so** [comment]
Thank you for your update on the progress of the original issue, appreciated :)
I certainly look into my timezone problem, thank you for your detailed explanation into this issue.

**Comment by 0x2142** [comment]
Hello again! I have published version [v0.2.6](https://github.com/0x2142/frigate-notify/releases/tag/v0.2.6), which should hopefully fix the zone issue - and maybe the timezone one as well! I added a few additional things to hopefully help ensure that the timezone gets applied correctly if you're using the `TZ` docker environment variable. 

I also did include a new configuration option to modify the time format in the notifications. Please see the [docs](https://frigate-notify.0x2142.com/config/#general) for how to configure this.

Thanks for your patience! Let me know if you're still having any issues

**Comment by Tempura-so** [comment]
I've updated the frigate-notify image to v0.2.6, the zones, timezone and time format are working perfectly.  I  am delighted, thank you for your time and assistance in this matter.

**Comment by 0x2142** [comment]
Perfect! Thanks so much for letting me know 😊

Feel free to reach out if you need anything else!

**Comment by Tempura-so** [comment]
Once again thank you, frigate-notify is a perfect companion to frigate nvr.
