### ISSUE TITLE
Failed to load config file! Error: config.yml: file not found

### ISSUE THREAD

**Issue by 35nine** [0x2142/frigate-notify#49]
Hi. Disclaimer - not an expert, using portainer.  

Have this error:

Failed to load config file! Error: config.yml: file not found

I've double checked typos, have the config.yml in the folder below, config.yml has rw-r-r

version: "3.0"
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    container_name: frigate-notify
    environment:
      - TZ=Etc/UTC
    volumes:
      - "/home/1/frigate-email:/config/app/"
    restart: unless-stopped

Any thoughts please welcomed? Ready to facepalm if I'm missing something obvious!

**Comment by freefd** [comment]
Hi @35nine, the image has the following built-in settings:
```
$ podman image inspect ghcr.io/0x2142/frigate-notify:latest -f '{{ .Config.WorkingDir }}'
/app
```
As for the business logic of the application, it will try to find `config.yml` in the working directory if it is not overridden. This behavior is also mentioned in the documentation, please check (https://frigate-notify.0x2142.com/install/).

You have 2 ways to solve this issue:
1. Add an environment variable `FN_CONFIGFILE` with the content `/config/app/config.yml`.
2. Provide the volumes configuration as `/home/1/frigate-email/config.yml:/app/config.yml`.

**NOTE**:
Please do not try to mount the entire `/home/1/frigate-email` directory into `/app` as this will override the `/app/frigate-notify` binary and break the container's Entrypoint:
```
$ podman image inspect ghcr.io/0x2142/frigate-notify:latest -f '{{ .Config.Entrypoint }}'
[/app/frigate-notify]
```

**Comment by 0x2142** [comment]
Hi there @35nine - Thanks for using this app! And thank you @freefd for jumping in to help here 😊

By default the app looks for the config file at `/app/config.yml`. If you're running the binary, this is fine - but with docker it needs to be overridden. Both options provided by @freefd should resolve this for you. I run mine with the first method & I'll provide a sample of my docker compose file below using your config path:

```text
version: "3.0"
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    environment:
      - 'FN_CONFIGFILE=/app/config/config.yml'
      - 'TZ=America/New_York'
    volumes:
      - /home/1/frigate-email:/app/config
    restart: unless-stopped
```

Hope that helps! Let us know if you're still having trouble

**Comment by 35nine** [comment]
@freefd and @0x2142 

Awesome, no more errors in logs, time to experiment now.  Certainly helped!  Using this fixed me up:

volumes:
      - /home/1/frigate-email/config.yml:/app/config.yml

Have a good day both, appreciate the replies
