### ISSUE TITLE
Web API default interval is actually 0

### ISSUE THREAD

**Issue by mike2307** [0x2142/frigate-notify#55]
The documentation states that the default interval for the web API is 30 seconds.
That seemed fine to me so I didn't add it to my configuration.

It turned out that when omitting the Web API interval in the config, the resulting interval is 0.
This causes some endless polling without a break.

Either the documentation should be adjusted or there's an issue with the handling of the default value of that property.

**Comment by 0x2142** [comment]
Ahh, good catch. I'm currently working on a new release, so I'll add in a quick fix for this. Thanks for reporting it!
