### ISSUE TITLE
Where are the Installation Docs? 

### ISSUE THREAD

**Issue by tokenwizard** [0x2142/frigate-notify#77]
When I click the link that says "Install/Setup" I just get this:

![image](https://github.com/0x2142/frigate-notify/assets/24832561/21adc909-7442-4847-85a7-bdd68f60c1c2)

**Comment by 0x2142** [comment]
Hi - Good catch. I just updated the docs site yesterday, and must have missed a link. I'll update that now.

Install docs are here: https://frigate-notify.0x2142.com/latest/install/

**Comment by tokenwizard** [comment]
Hot it, thanks! Once I realized it was docker-compose and you had a config example I managed to work it out myself. But glad the link works now!
