### ISSUE TITLE
[Feature] ntfy user authentification

### ISSUE THREAD

**Issue by mabed-fr** [0x2142/frigate-notify#82]
Hello

Can you add the feature for send trought a ntfy with user password ? (i have my personal ntfy)

Mathieu

**Comment by freefd** [comment]
May I ask you to change the wording to “Support custom HTTP headers for ntfy notifier”? :)

Are you talking about the Authorization header you would like to achieve: https://docs.ntfy.sh/publish/#authentication

For example, the same mechanism is already supported by Webhook notifier: https://frigate-notify.0x2142.com/latest/config/file/#webhook

**Comment by 0x2142** [comment]
Ah, yeah if it's just additional headers then that will be easy to add. I'll put this on my list for the next release 👍

**Comment by mabed-fr** [comment]
Thank you !

**Comment by 0x2142** [comment]
Added in [v0.3.1](https://github.com/0x2142/frigate-notify/releases/tag/v0.3.1)
