### ISSUE TITLE
Anyone else seeing erroneous event notifications? 

### ISSUE THREAD

**Issue by tokenwizard** [0x2142/frigate-notify#84]
I have two of my cameras configured to send notifications via Gotify, and they are working, but this morning I have gotten about 12 notifications that say a Person was detected on one of the cameras. When I click the Camera link in the notification, I see all the events for that camera, but there are not any events saved for today. The most recent event was yesterday evening and was a car. 

So I'm not sure why these erroneous event notifications are being generated when there is actually no event in Frigate.

**Comment by mabed-fr** [comment]
I've actually had this happen before.

This should disappear once /review is in place.

However since the bug fix for the moment I no longer have any.

**Comment by freefd** [comment]
Hi, has this issue been resolved? Can it be closed?

**Comment by mabed-fr** [comment]
Yes !
